// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/object_box/models/product_model_box.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5765332606286817175),
      name: 'ProductModelBox',
      lastPropertyId: const obx_int.IdUid(8, 3009362734190904145),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6650496910845443915),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1550522845209331479),
            name: 'productId',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 654939378106728333),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7183890894504076007),
            name: 'price',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4628527997995307605),
            name: 'discountPercentage',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6789270466501870773),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4208977624522901393),
            name: 'imageUrl',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 3009362734190904145),
            name: 'quantity',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 5765332606286817175),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ProductModelBox: obx_int.EntityDefinition<ProductModelBox>(
        model: _entities[0],
        toOneRelations: (ProductModelBox object) => [],
        toManyRelations: (ProductModelBox object) => {},
        getId: (ProductModelBox object) => object.id,
        setId: (ProductModelBox object, int id) {
          object.id = id;
        },
        objectToFB: (ProductModelBox object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          final imageUrlOffset = fbb.writeString(object.imageUrl);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.productId);
          fbb.addOffset(2, nameOffset);
          fbb.addFloat64(3, object.price);
          fbb.addFloat64(4, object.discountPercentage);
          fbb.addOffset(5, descriptionOffset);
          fbb.addOffset(6, imageUrlOffset);
          fbb.addInt64(7, object.quantity);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final productIdParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final priceParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final discountPercentageParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final imageUrlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final quantityParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final object = ProductModelBox(
              id: idParam,
              productId: productIdParam,
              name: nameParam,
              price: priceParam,
              discountPercentage: discountPercentageParam,
              description: descriptionParam,
              imageUrl: imageUrlParam,
              quantity: quantityParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ProductModelBox] entity fields to define ObjectBox queries.
class ProductModelBox_ {
  /// See [ProductModelBox.id].
  static final id =
      obx.QueryIntegerProperty<ProductModelBox>(_entities[0].properties[0]);

  /// See [ProductModelBox.productId].
  static final productId =
      obx.QueryIntegerProperty<ProductModelBox>(_entities[0].properties[1]);

  /// See [ProductModelBox.name].
  static final name =
      obx.QueryStringProperty<ProductModelBox>(_entities[0].properties[2]);

  /// See [ProductModelBox.price].
  static final price =
      obx.QueryDoubleProperty<ProductModelBox>(_entities[0].properties[3]);

  /// See [ProductModelBox.discountPercentage].
  static final discountPercentage =
      obx.QueryDoubleProperty<ProductModelBox>(_entities[0].properties[4]);

  /// See [ProductModelBox.description].
  static final description =
      obx.QueryStringProperty<ProductModelBox>(_entities[0].properties[5]);

  /// See [ProductModelBox.imageUrl].
  static final imageUrl =
      obx.QueryStringProperty<ProductModelBox>(_entities[0].properties[6]);

  /// See [ProductModelBox.quantity].
  static final quantity =
      obx.QueryIntegerProperty<ProductModelBox>(_entities[0].properties[7]);
}
